[tool.aerich]
tortoise_orm = "app.database.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

[tool.black]
line-length = 120
skip-string-normalization = true
exclude = '''
/(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.nox
    | \.tox
    | \.venv
    | \.svn
    | _build
    | buck-out
    | build
    | dist
    | .*venv.*
)/
'''

[tool.isort]
line_length = 120
profile = "black"

[tool.pytest.ini_options]
asyncio_mode = "auto"
